version: '3.8'

services:
  vector-db:
    image: qdrant/qdrant:latest
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:6333/readiness"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 15s
    ports:
      - "6333:6333"  # For internal communication

  files-db-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      vector-db:
        condition: service_healthy
    volumes:
      - ${PROJECT_DIR:-./}:/project:ro  # Mount the project directory read-only
      - app_data:/app/data              # For persistent application data
    environment:
      - VECTOR_DB_HOST=vector-db
      - VECTOR_DB_PORT=6333
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2  # Default code embedding model
      - QUANTIZATION=true                                       # Enable quantization by default
      - BINARY_EMBEDDINGS=false                                 # Disable binary embeddings by default
      - DEBUG=true                                              # Enable debug mode
      - PROJECT_PATH=/project
      - IGNORE_PATTERNS=.git,node_modules,__pycache__,venv,dist,build,*.pyc,.files-db-mcp
      - PORT=8000                                               # Explicitly set the port
    ports:
      - "3000:8000"  # Map container port 8000 to host port 3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  qdrant_data:
  app_data: